import type { Carton, CushionProfile, OrderLine, Product } from '@/packing'

export type PokemonCenterBoxDetail = {
  id: string
  title: string
  productCode: string
  releaseDate: string
  priceYen: number
  sizeText: string
  sizeCm: { length: number; width: number; height: number }
  weightText: string
  weightGrams: number
  packsPerBox: number
  cardsPerPack: number
  url: string
}

export const products: Product[] = [
  {
    id: 'pokemon-booster-box',
    brand: 'Pokemon',
    name: 'ポケモンカードゲーム 拡張パックBOX',
    category: '拡張パックBOX',
    size: { length: 140, width: 78, height: 126 },
    priceYen: 5400,
    weight: 360,
    fragility: 'medium',
    color: '#e45d50',
    note: 'サンプル寸法。実運用ではSKUごとの実測値に置き換えます。',
  },
  {
    id: 'pokemon-premium-set',
    brand: 'Pokemon',
    name: 'ポケモンカードゲーム プレミアムセット',
    category: '限定セット',
    size: { length: 188, width: 122, height: 58 },
    weight: 420,
    fragility: 'high',
    color: '#f39b4a',
    note: '角潰れを避けるため、厚めの緩衝材を優先したい商品です。',
  },
  {
    id: 'onepiece-booster-box',
    brand: 'ONE PIECE',
    name: 'ONE PIECEカードゲーム ブースターボックス',
    category: 'ブースターボックス',
    size: { length: 150, width: 82, height: 128 },
    weight: 390,
    fragility: 'medium',
    color: '#5698d4',
    note: 'サンプル寸法。タイトル別で箱サイズ差分を持てる設計です。',
  },
  {
    id: 'onepiece-double-pack',
    brand: 'ONE PIECE',
    name: 'ONE PIECEカードゲーム ダブルパック',
    category: 'ダブルパック',
    size: { length: 145, width: 95, height: 42 },
    weight: 180,
    fragility: 'low',
    color: '#5a78a9',
    note: '薄型商品のため、上面の潰れと空隙量が安定性に影響します。',
  },
  {
    id: 'onepiece-op15-adventure-on-gods-island',
    brand: 'ONE PIECE',
    name: 'ONE PIECEカードゲーム OP-15 神の島の冒険',
    category: 'ブースターパックBOX',
    size: { length: 70, width: 70, height: 150 },
    weight: 250,
    fragility: 'medium',
    color: '#d38a47',
    note: '長さ7cm・幅7cm・高さ15cm・重量250gの指定値を反映。',
  },
  {
    id: 'dragonball-booster-box',
    brand: 'Dragon Ball',
    name: 'ドラゴンボールカードゲーム ブースターボックス',
    category: 'ブースターボックス',
    size: { length: 148, width: 80, height: 125 },
    weight: 370,
    fragility: 'medium',
    color: '#7eb057',
    note: 'Pokemon / ONE PIECE と近い寸法でも個別管理できます。',
  },
  {
    id: 'dragonball-starter-deck',
    brand: 'Dragon Ball',
    name: 'ドラゴンボールカードゲーム スターターデッキ',
    category: 'スターターデッキ',
    size: { length: 140, width: 82, height: 32 },
    weight: 160,
    fragility: 'low',
    color: '#98bf62',
    note: '小型商品を同梱するときの隙間調整に使いやすい想定です。',
  },
]

export const cartons: Carton[] = [
  {
    id: 'yamato-compact-box',
    code: '宅急便コンパクト',
    label: '専用BOX',
    service: '宅急便コンパクト',
    outer: { length: 200, width: 250, height: 50 },
    inner: { length: 193, width: 247, height: 47 },
    maxWeight: null,
    priceYen: 70,
    note: 'ヤマト運輸の専用資材。公式案内では重量制限なし。',
  },
  {
    id: 'yamato-box-6',
    code: 'クロネコボックス',
    label: '6',
    service: '宅急便 60サイズ相当',
    outer: { length: 200, width: 270, height: 130 },
    inner: { length: 194, width: 264, height: 118 },
    maxWeight: 2000,
    priceYen: 140,
    note: 'ヤマト運輸公式の小型箱。小さめのBOX商品向け。',
  },
  {
    id: 'yamato-box-8',
    code: 'クロネコボックス',
    label: '8',
    service: '宅急便 80サイズ相当',
    outer: { length: 270, width: 380, height: 150 },
    inner: { length: 264, width: 374, height: 138 },
    maxWeight: 5000,
    priceYen: 160,
    note: 'ヤマト運輸公式の標準箱。複数SKUの混載候補。',
  },
  {
    id: 'yamato-box-10',
    code: 'クロネコボックス',
    label: '10',
    service: '宅急便 100サイズ相当',
    outer: { length: 270, width: 380, height: 350 },
    inner: { length: 260, width: 370, height: 330 },
    maxWeight: 10000,
    priceYen: 220,
    note: 'ヤマト運輸公式の中型箱。緩衝材を厚めに入れやすい。',
  },
  {
    id: 'yamato-box-12',
    code: 'クロネコボックス',
    label: '12',
    service: '宅急便 120サイズ相当',
    outer: { length: 380, width: 530, height: 290 },
    inner: { length: 370, width: 520, height: 270 },
    maxWeight: 15000,
    priceYen: 260,
    note: 'ヤマト運輸公式の大型箱。複数BOXの同梱向け。',
  },
  {
    id: 'yamato-box-14',
    code: 'クロネコボックス',
    label: '14',
    service: '宅急便 140サイズ相当',
    outer: { length: 400, width: 600, height: 400 },
    inner: { length: 390, width: 590, height: 380 },
    maxWeight: 20000,
    priceYen: 370,
    note: 'ヤマト運輸公式の特大型箱。大量同梱や余白確保向け。',
  },
]

export const cushions: CushionProfile[] = [
  {
    id: 'air-cap-light',
    name: 'プチプチ（気泡緩衝材）5mm',
    sidePadding: 5,
    topPadding: 8,
    bottomPadding: 8,
    stabilityBonus: 8,
    voidFillUnitVolume: 300_000,
    note: '一般的な軽量保護。単品や標準箱向け。',
  },
  {
    id: 'paper-pad',
    name: 'クラフト紙緩衝材',
    sidePadding: 8,
    topPadding: 12,
    bottomPadding: 10,
    stabilityBonus: 10,
    voidFillUnitVolume: 240_000,
    note: '隙間埋め性能が高く、混載時に安定しやすい。',
  },
  {
    id: 'epe-foam',
    name: '発泡PEフォーム 10mm',
    sidePadding: 10,
    topPadding: 12,
    bottomPadding: 12,
    stabilityBonus: 15,
    voidFillUnitVolume: 200_000,
    note: '角潰れを避けたい限定品や高単価商品向け。',
  },
]

export const defaultOrderLines: OrderLine[] = [
  { productId: 'pokemon-booster-box', quantity: 2, useItemWrap: false },
  { productId: 'pokemon-premium-set', quantity: 1, useItemWrap: false },
  { productId: 'onepiece-booster-box', quantity: 1, useItemWrap: false },
  { productId: 'onepiece-double-pack', quantity: 0, useItemWrap: false },
  {
    productId: 'onepiece-op15-adventure-on-gods-island',
    quantity: 0,
    useItemWrap: false,
  },
  { productId: 'dragonball-booster-box', quantity: 1, useItemWrap: false },
  { productId: 'dragonball-starter-deck', quantity: 2, useItemWrap: false },
]

export const pokemonCenterBoxDetails: PokemonCenterBoxDetail[] = [
  {
    id: 'pokemon-hot-wind-arena-box',
    title:
      'ポケモンカードゲーム スカーレット＆バイオレット 強化拡張パック 熱風のアリーナ BOX',
    productCode: '9900000006013',
    releaseDate: '2025-03-14',
    priceYen: 5400,
    sizeText: '13.7×14×3.6 cm',
    sizeCm: { length: 13.7, width: 14, height: 3.6 },
    weightText: '300 g',
    weightGrams: 300,
    packsPerBox: 30,
    cardsPerPack: 5,
    url: 'https://www.pokemoncenter-online.com/9900000006013.html',
  },
  {
    id: 'pokemon-stellar-miracle-box',
    title:
      'ポケモンカードゲーム スカーレット&バイオレット 拡張パック ステラミラクル BOX',
    productCode: '4521329331676',
    releaseDate: '2024-07-19',
    priceYen: 5400,
    sizeText: '13.7×14×3.6 cm',
    sizeCm: { length: 13.7, width: 14, height: 3.6 },
    weightText: '300 g',
    weightGrams: 300,
    packsPerBox: 30,
    cardsPerPack: 5,
    url: 'https://www.pokemoncenter-online.com/4521329331676.html',
  },
  {
    id: 'pokemon-inferno-x-box',
    title: 'ポケモンカードゲーム MEGA 拡張パック インフェルノX BOX',
    productCode: '9900000006679',
    releaseDate: '2025-09-26',
    priceYen: 5400,
    sizeText: '13.7×14×3.6 cm',
    sizeCm: { length: 13.7, width: 14, height: 3.6 },
    weightText: '300 g',
    weightGrams: 300,
    packsPerBox: 30,
    cardsPerPack: 5,
    url: 'https://www.pokemoncenter-online.com/9900000006679.html',
  },
  {
    id: 'pokemon-ninja-spinner-box',
    title: 'ポケモンカードゲーム MEGA 拡張パック ニンジャスピナー BOX',
    productCode: '9900000007898',
    releaseDate: '2026-03-13',
    priceYen: 5400,
    sizeText: '13.7×14×3.6 cm',
    sizeCm: { length: 13.7, width: 14, height: 3.6 },
    weightText: '300 g',
    weightGrams: 300,
    packsPerBox: 30,
    cardsPerPack: 5,
    url: 'https://www.pokemoncenter-online.com/9900000007898.html',
  },
  {
    id: 'pokemon-munikisu-zero-box',
    title: 'ポケモンカードゲーム MEGA 拡張パック ムニキスゼロ BOX',
    productCode: '9900000007003',
    releaseDate: '2026-01-23',
    priceYen: 5400,
    sizeText: '13.7×14×3.6 cm',
    sizeCm: { length: 13.7, width: 14, height: 3.6 },
    weightText: '300 g',
    weightGrams: 300,
    packsPerBox: 30,
    cardsPerPack: 5,
    url: 'https://www.pokemoncenter-online.com/9900000007003.html',
  },
  {
    id: 'pokemon-terastal-fes-ex-box',
    title:
      'ポケモンカードゲーム スカーレット＆バイオレット ハイクラスパック テラスタルフェスex BOX',
    productCode: '9900000006167',
    releaseDate: '2024-12-06',
    priceYen: 5500,
    sizeText: '7.4×13.9×4.3 cm',
    sizeCm: { length: 7.4, width: 13.9, height: 4.3 },
    weightText: '190 g',
    weightGrams: 190,
    packsPerBox: 10,
    cardsPerPack: 10,
    url: 'https://www.pokemoncenter-online.com/9900000006167.html',
  },
]
