import { Platform, StatusBar, StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  numericInputContainer: { flex: 1, minWidth: 0 },
  invalidInput: { borderColor: '#ba3434' },
  inputError: { color: '#a42d2d', fontSize: 11 },
  safeArea: {
    flex: 1,
    backgroundColor: '#f4f5f0',
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight ?? 0) : 0,
  },
  scrollContent: {
    paddingBottom: 28,
    paddingHorizontal: 14,
    paddingTop: 14,
  },
  page: {
    alignSelf: 'center',
    gap: 16,
    maxWidth: 1180,
    width: '100%',
  },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  languageSwitch: {
    backgroundColor: '#e7ebe5',
    borderColor: '#cfd8cf',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    padding: 3,
  },
  languageOption: {
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  languageOptionActive: {
    backgroundColor: '#0f766e',
  },
  languageOptionText: {
    color: '#2f3b36',
    fontSize: 13,
    fontWeight: '700',
  },
  languageOptionActiveText: {
    color: '#ffffff',
  },
  hero: {
    gap: 12,
  },
  heroWide: {
    alignItems: 'stretch',
    flexDirection: 'row',
  },
  heroPanel: {
    backgroundColor: '#ffffff',
    borderColor: '#d6ded6',
    borderRadius: 8,
    borderWidth: 1,
    flex: 2,
    gap: 12,
    padding: 18,
  },
  summaryPanel: {
    backgroundColor: '#e8f2ef',
    borderColor: '#b9d3ca',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: 8,
    padding: 16,
  },
  heroTitle: {
    color: '#15201b',
    fontSize: 27,
    fontWeight: '800',
    lineHeight: 33,
  },
  eyebrow: {
    color: '#0f766e',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  lead: {
    color: '#46514b',
    fontSize: 15,
    lineHeight: 23,
  },
  heroStats: {
    gap: 10,
  },
  heroStat: {
    backgroundColor: '#f7f8f4',
    borderColor: '#dfe5de',
    borderRadius: 8,
    borderWidth: 1,
    padding: 12,
  },
  heroStatValue: {
    color: '#111c18',
    fontSize: 22,
    fontWeight: '800',
    marginTop: 3,
  },
  workspace: {
    gap: 16,
  },
  workspaceWide: {
    alignItems: 'flex-start',
    flexDirection: 'row',
  },
  workspaceColumn: {
    gap: 16,
    minWidth: 0,
  },
  workspaceColumnWide: {
    flex: 1,
  },
  section: {
    backgroundColor: '#ffffff',
    borderColor: '#d8dfd8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 14,
    padding: 14,
  },
  sectionHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'space-between',
  },
  sectionHeaderStacked: {
    flexDirection: 'column',
  },
  sectionHeaderTitleRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    width: '100%',
  },
  sectionTitleGroup: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  sectionTitleGroupStacked: {
    flex: 1,
  },
  sectionTitle: {
    color: '#16221d',
    fontSize: 20,
    flexShrink: 1,
    fontWeight: '800',
    lineHeight: 25,
  },
  sectionActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    maxWidth: '100%',
  },
  sectionActionsStacked: {
    alignSelf: 'stretch',
    justifyContent: 'flex-start',
    width: '100%',
  },
  collapseToggle: {
    alignItems: 'center',
    backgroundColor: '#f7f8f4',
    borderColor: '#cdd8cf',
    borderRadius: 8,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  collapseToggleText: {
    color: '#17221d',
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 20,
  },
  appButton: {
    alignItems: 'center',
    backgroundColor: '#eef2ee',
    borderColor: '#cdd8cf',
    borderRadius: 8,
    borderWidth: 1,
    flexShrink: 1,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 13,
    paddingVertical: 9,
  },
  appButtonPrimary: {
    backgroundColor: '#0f766e',
    borderColor: '#0f766e',
  },
  appButtonGhost: {
    backgroundColor: '#ffffff',
  },
  appButtonText: {
    color: '#26332e',
    flexShrink: 1,
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
  },
  appButtonPrimaryText: {
    color: '#ffffff',
  },
  appButtonGhostText: {
    color: '#0f766e',
  },
  pressed: {
    opacity: 0.72,
  },
  productGrid: {
    gap: 12,
  },
  productCard: {
    backgroundColor: '#fbfcfa',
    borderColor: '#dbe3db',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  productHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  productHeaderCompact: {
    alignItems: 'flex-start',
    flexDirection: 'column',
  },
  brandChip: {
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  brandChipText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
  },
  productName: {
    color: '#17221e',
    flex: 1,
    fontSize: 17,
    fontWeight: '800',
    minWidth: 0,
    width: '100%',
  },
  productCategory: {
    color: '#59645e',
    fontSize: 13,
  },
  fieldGroupLabel: {
    color: '#34413a',
    fontSize: 12,
    fontWeight: '800',
  },
  dimensionGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  dimensionGridCompact: {
    flexDirection: 'column',
  },
  numberField: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  numberFieldLabel: {
    color: '#5d6861',
    fontSize: 11,
    fontWeight: '700',
  },
  numberInput: {
    backgroundColor: '#ffffff',
    borderColor: '#cbd5cd',
    borderRadius: 8,
    borderWidth: 1,
    color: '#15201b',
    fontSize: 15,
    minHeight: 42,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  productMetaGrid: {
    gap: 8,
  },
  productMetaBlock: {
    backgroundColor: '#f2f5f2',
    borderRadius: 8,
    gap: 3,
    padding: 10,
  },
  metaText: {
    color: '#4b5650',
    fontSize: 13,
    lineHeight: 19,
  },
  stepper: {
    alignItems: 'center',
    alignSelf: 'stretch',
    flexDirection: 'row',
    gap: 8,
  },
  stepperButton: {
    alignItems: 'center',
    backgroundColor: '#1f2937',
    borderRadius: 8,
    height: 42,
    justifyContent: 'center',
    width: 44,
  },
  stepperButtonText: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '800',
  },
  quantityInput: {
    backgroundColor: '#ffffff',
    borderColor: '#cbd5cd',
    borderRadius: 8,
    borderWidth: 1,
    color: '#15201b',
    flex: 1,
    flexBasis: 0,
    fontSize: 17,
    fontWeight: '800',
    minHeight: 42,
    minWidth: 0,
    paddingHorizontal: 12,
    textAlign: 'center',
  },
  wrapControl: {
    alignItems: 'center',
    backgroundColor: '#edf5f3',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    padding: 10,
  },
  wrapControlCompact: {
    alignItems: 'flex-start',
    flexDirection: 'column',
  },
  wrapEnabled: {
    color: '#0f766e',
    fontSize: 14,
    fontWeight: '800',
  },
  wrapDisabled: {
    color: '#7b817a',
    fontSize: 14,
    fontWeight: '800',
  },
  strategySwitch: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  strategyNote: {
    color: '#56615b',
    fontSize: 13,
    lineHeight: 20,
  },
  cardStack: {
    gap: 10,
  },
  selectableCard: {
    backgroundColor: '#fbfcfa',
    borderColor: '#d7dfd8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  selectableCardActive: {
    backgroundColor: '#eff8f6',
    borderColor: '#0f766e',
    borderWidth: 2,
  },
  selectableHead: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'space-between',
  },
  cardBadge: {
    color: '#2563eb',
    fontSize: 12,
    fontWeight: '800',
  },
  selectableTitle: {
    color: '#17221d',
    flex: 1,
    fontSize: 18,
    fontWeight: '800',
    minWidth: 0,
    textAlign: 'left',
  },
  selectableSubtitle: {
    color: '#58635d',
    fontSize: 13,
    lineHeight: 19,
  },
  metricList: {
    gap: 8,
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  metricRow: {
    alignItems: 'center',
    backgroundColor: '#f1f4f1',
    borderRadius: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'space-between',
    padding: 10,
  },
  metricTile: {
    backgroundColor: '#f1f4f1',
    borderRadius: 8,
    gap: 4,
    minWidth: 132,
    padding: 10,
  },
  metricLabel: {
    color: '#667069',
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '700',
  },
  metricValue: {
    color: '#17211d',
    flexShrink: 1,
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'right',
  },
  emptyState: {
    backgroundColor: '#f6f7f4',
    borderColor: '#d9e0d8',
    borderRadius: 8,
    borderWidth: 1,
    gap: 6,
    padding: 16,
  },
  emptyTitle: {
    color: '#17221d',
    fontSize: 16,
    fontWeight: '800',
  },
  emptyBody: {
    color: '#59645e',
    fontSize: 14,
    lineHeight: 21,
  },
  bulletText: {
    color: '#445049',
    fontSize: 14,
    lineHeight: 22,
  },
  serviceText: {
    color: '#4b5650',
    fontSize: 14,
    lineHeight: 21,
  },
  reasonList: {
    gap: 5,
  },
  layerStack: {
    gap: 12,
  },
  visualizedBox: {
    gap: 12,
  },
  scenePanel: {
    backgroundColor: '#fbfcfa',
    borderColor: '#d7ded7',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  sceneLoading: {
    alignItems: 'center',
    backgroundColor: '#eef2ee',
    borderColor: '#cbd8d0',
    borderRadius: 8,
    borderWidth: 1,
    height: 340,
    justifyContent: 'center',
    padding: 18,
    width: '100%',
  },
  layerCard: {
    backgroundColor: '#fbfcfa',
    borderColor: '#d7ded7',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  layerHeader: {
    gap: 4,
  },
  layerTitle: {
    color: '#17221d',
    fontSize: 16,
    fontWeight: '800',
  },
  layerRange: {
    color: '#59645e',
    fontSize: 12,
    lineHeight: 18,
  },
  planBoard: {
    backgroundColor: '#f3eee6',
    borderColor: '#b9a997',
    borderRadius: 8,
    borderWidth: 2,
    overflow: 'hidden',
    position: 'relative',
    width: '100%',
  },
  effectiveArea: {
    backgroundColor: '#ffffff',
    borderColor: '#b2cfc4',
    borderStyle: 'dashed',
    borderWidth: 1,
    pointerEvents: 'none',
    position: 'absolute',
  },
  voidBlock: {
    backgroundColor: '#c3d9d1',
    borderColor: '#82aa9d',
    borderWidth: 1,
    pointerEvents: 'none',
    position: 'absolute',
  },
  planItemShell: {
    borderColor: '#ffffff',
    borderRadius: 6,
    borderWidth: 1,
    overflow: 'hidden',
    position: 'absolute',
  },
  planItemShellWrapped: {
    borderColor: '#c4892f',
    borderWidth: 2,
  },
  planItem: {
    alignItems: 'center',
    borderRadius: 4,
    justifyContent: 'center',
    overflow: 'hidden',
    padding: 3,
    position: 'absolute',
  },
  planItemBrand: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '900',
  },
  planItemCategory: {
    color: '#ffffff',
    fontSize: 9,
    fontWeight: '700',
  },
  planItemSize: {
    color: '#ffffff',
    fontSize: 8,
  },
  planLegend: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  threeDLegend: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  legendText: {
    backgroundColor: '#eff2ee',
    borderRadius: 6,
    color: '#46514b',
    fontSize: 11,
    fontWeight: '700',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  comparisonGrid: {
    gap: 10,
  },
  comparisonGridWide: {
    flexDirection: 'row',
  },
  comparisonCard: {
    backgroundColor: '#fbfcfa',
    borderColor: '#d7dfd8',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: 10,
    padding: 12,
  },
  comparisonCardHighlight: {
    backgroundColor: '#eef8f6',
    borderColor: '#0f766e',
  },
  comparisonTitle: {
    color: '#17221d',
    fontSize: 17,
    fontWeight: '800',
    lineHeight: 23,
  },
  splitBoxGrid: {
    gap: 10,
    marginTop: 12,
  },
  splitBoxGridWide: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  splitBoxCard: {
    backgroundColor: '#fbfcfa',
    borderColor: '#d7dfd8',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: 10,
    minWidth: 250,
    padding: 12,
  },
  splitBoxHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  splitBoxTitle: {
    color: '#2563eb',
    fontSize: 13,
    fontWeight: '800',
  },
  splitBoxName: {
    color: '#17221d',
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 22,
  },
  splitItemList: {
    gap: 7,
  },
  splitItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  miniColorDot: {
    borderRadius: 5,
    height: 10,
    width: 10,
  },
  splitItemName: {
    color: '#34413a',
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
  },
  splitItemQty: {
    color: '#59645e',
    fontSize: 12,
    fontWeight: '800',
  },
  catalogGrid: {
    gap: 12,
  },
  catalogGridWide: {
    flexDirection: 'row',
  },
  catalogPanel: {
    flex: 1,
    gap: 10,
  },
  catalogTitle: {
    color: '#17221d',
    fontSize: 17,
    fontWeight: '800',
  },
  catalogItem: {
    backgroundColor: '#f6f8f5',
    borderColor: '#dde4dc',
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    padding: 10,
  },
  catalogItemTitle: {
    color: '#17221d',
    fontSize: 14,
    fontWeight: '800',
  },
  catalogNote: {
    color: '#59645e',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 2,
  },
})
